version: '3.9'

services:
  mongodb:
    container_name: mongodb
    image: mongo
    ports:
      - '${MONGO_PORT}:27017'
    volumes:
      - mongo_volume:/data/db
    networks:
      - backend
    healthcheck:
      test: ["CMD", "mongo", "--eval", "db.adminCommand('ping')"]
      interval: 10s
      timeout: 5s
      retries: 5

  mongo-express:
    image: mongo-express
    container_name: mongo-express
    restart: always
    ports:
      - "${MONGO_EXPRESS_PORT}:8081"
    environment:
      ME_CONFIG_MONGODB_SERVER: mongodb
      ME_CONFIG_BASICAUTH_USERNAME: ${MONGO_ADMIN_USERNAME}
      ME_CONFIG_BASICAUTH_PASSWORD: ${MONGO_ADMIN_PASSWORD}
      ME_CONFIG_MONGODB_URL: ${MONGO_URI}
    depends_on:
      - mongodb
    networks:
      - backend

  main-app:
    build:
      context: ..
      dockerfile: Dockerfile
    container_name: main-app
    ports:
      - "${API_PORT}:8000"
    command: "uvicorn --factory app.main:create_app --reload --host 0.0.0.0 --port 8000"
    env_file:
      - ../.env
    volumes:
      - ../src/:/src/
    networks:
      - backend
    depends_on:
      - mongodb

volumes:
  mongo_volume:

networks:
  backend:
    driver: bridge