version: '3.9'

services:
  main-app:
    build:
      context: ..
      dockerfile: Dockerfile
    container_name: main-app
    ports: 
      - "8000:8000"
    command: "python3 app/main.py"
    env_file:
      - ../.env
    volumes:
      - ../src/:/src/
    networks:
      - backend

networks:
  backend:
    driver: bridge