version: '3.9'

services:
  main-app:
    build:
      context: ..
      dockerfile: Dockerfile
    container_name: main-app
    ports: 
      - ${API_PORT}:8000
    # command: "python3 app/main.py"
    command: "uvicorn --factory api.v1.main:create_app --reload --host 0.0.0.0 --port 8000"
    env_file:
      - ../.env
    volumes:
      - ../src/:/src/
    networks:
      - backend

networks:
  backend:
    driver: bridge