version: '3.9'

services:
  mongodb:
    image: mongo
    container_name: mongodb
    ports:
      - ${MONGO_PORT}:27017
    volumes:
      - mongo_volume:/data/db
    networks:
      - backend

  mongo-express:
    image: mongo-express
    container_name: mongo-express
    # restart: always
    ports:
      - ${MONGO_EXPRESS_PORT}:8081
    environment:
      ME_CONFIG_MONGODB_SERVER: mongodb
      ME_CONFIG_BASICAUTH_USERNAME: ${MONGO_ADMIN_USERNAME}
      ME_CONFIG_BASICAUTH_PASSWORD: ${MONGO_ADMIN_PASSWORD}
      ME_CONFIG_MONGODB_URL: ${MONGO_URI}
    depends_on:
      - mongodb
    networks:
      - backend

volumes:
  mongo_volume:

networks:
  backend:
    driver: bridge