name: Run Ruff and Pytest

on: [push, pull_request]

jobs:
  test:
    name: Run Ruff and Pytest
    runs-on: ubuntu-latest
    env:
      PYTHONPATH: ${{ secrets.PYTHONPATH }}
      APP_ENV: ${{ secrets.APP_ENV }}
      API_PORT: ${{ secrets.API_PORT }}
      MONGO_EXPRESS_PORT: ${{ secrets.MONGO_EXPRESS_PORT }}
      MONGO_PORT: ${{ secrets.MONGO_PORT }}
      MONGO_URI: ${{ secrets.MONGO_URI }}
      MONGO_ADMIN_USERNAME: ${{ secrets.MONGO_ADMIN_USERNAME }}
      MONGO_ADMIN_PASSWORD: ${{ secrets.MONGO_ADMIN_PASSWORD }}
      ZOOKEEPER_PORT: ${{ secrets.ZOOKEEPER_PORT }}
      KAFKA_PORT: ${{ secrets.KAFKA_PORT }}
      KAFKA_UI_PORT: ${{ secrets.KAFKA_UI_PORT }}
      KAFKA_URI: ${{ secrets.KAFKA_URI }}

    steps:
      - name: Check out code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install Poetry
        run: |
          curl -sSL https://install.python-poetry.org | python3 -
          echo "${HOME}/.local/bin" >> $GITHUB_PATH
          poetry --version

      - name: Cache Poetry packages
        id: poetry-cache
        uses: actions/cache@v3
        with:
          path: |
            ~/.cache/pypoetry
            ~/.virtualenvs
          key: ${{ runner.os }}-poetry-${{ hashFiles('poetry.lock') }}
          restore-keys: |
            ${{ runner.os }}-poetry

      - name: Install Dependencies
        run: |
          poetry install --no-root

      - name: Run Ruff
        run: |
          poetry run ruff check .

      - name: Run Pytest
        run: |
          poetry run pytest
